# 40-ip-forwarding.conf - Enable IP forwarding permanently for the GNS3 NAT bridge to communicate with the host and the internet
# Installed to /etc/sysctl.d/40-ip-forwarding.conf
#

# Enable packet forwarding for IPv4
net.ipv4.ip_forward=1
# Enable packet forwarding for IPv6
net.ipv6.conf.all.forwarding=1
