# Don't do anything if not running interactively
case $- in
    *i*) ;;
      *) return;;
esac

/usr/local/bin/gns3welcome.py
echo "Please run 'sudo gns3restore' in case the menu is no longer showing"
