strict-order
user=gns3
except-interface=lo
bind-dynamic
interface=gns3br0
dhcp-range=192.168.122.2,192.168.122.254,255.255.255.0
dhcp-no-override
dhcp-authoritative
dhcp-lease-max=253
dhcp-leasefile=/var/lib/misc/gns3-dnsmasq.leases
