#! /bin/sh
### BEGIN INIT INFO
# Provides:          zerofree
# Required-Start:
# Required-Stop:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Compress the filesystem
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin/
. /lib/init/vars.sh

. /lib/lsb/init-functions

do_stop () {
	if [ -f /zerofree ]
	then
		echo "Compress disks"
		zerofree /dev/sda1
		zerofree /dev/sdb1
	fi
}

do_start() {
	if [ -f /zerofree ]
	then
	  rm /zerofree
  fi
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
