#!/bin/sh

command -v vmtoolsd >/dev/null 2>&1 || exit 0

if [ "$IFACE" == "eth0" ];
then
  IP=`ifconfig $IFACE | grep 'inet addr:' | cut -d: -f2 | cut -d' ' -f1`
  vmtoolsd --cmd "info-set guestinfo.gns3.$IFACE $IP"
fi
